services:
  cryptoapi:
    build: .
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=db
    env_file:
      - ./internal/database/DB_Config.env
      - ./internal/database/SecretHash.env
    # command: sh -c "./wait-for.sh db:5432 -- ./main"
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

  db:
    image: postgres:15-alpine
    env_file:
      - ./internal/database/DB_Config.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  postgres_data: