CREATE TABLE users (
    id SERIAL PRIMARY KEY,
    email VARCHAR(255) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL,
    registeredat VARCHAR(255) NOT NULL
);
CREATE TABLE user_favorites (
    user_id INTEGER NOT NULL,
    crypto_id INTEGER NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (user_id, crypto_id),  -- Композитный ключ
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);
CREATE TABLE refresh_tokens (
    id SERIAL PRIMARY KEY,
    user_id INTEGER NOT NULL,
    token VARCHAR(255) NOT NULL,
    expires_at TIMESTAMP WITHOUT TIME ZONE NOT NULL
);
CREATE TABLE cryptocurrencies (
    id SERIAl PRIMARY KEY,
    name VARCHAR(100)
);

INSERT INTO cryptocurrencies (id, name) VALUES
(1, 'bitcoin'),
(2, 'ethereum'),
(3, 'tether'),
(4, 'xrp'),
(5, 'binance-coin'),
(6, 'solana'),
(7, 'usd-coin'),
(8, 'dogecoin'),
(9, 'tron'),
(10, 'cardano'),
(11, 'steth'),
(12, 'wrapped-bitcoin'),
(13, 'chainlink'),
(14, 'unus-sed-leo'),
(15, 'avalanche'),
(16, 'stellar'),
(17, 'sui'),
(18, 'shiba-inu'),
(19, 'toncoin'),
(20, 'hedera-hashgraph'),
(21, 'bitcoin-cash'),
(22, 'hyperliquid'),
(23, 'litecoin'),
(24, 'bitcoin-bep2'),
(25, 'polkadot'),
(26, 'weth'),
(27, 'multi-collateral-dai'),
(28, 'bitget-token-new'),
(29, 'ethena-usde'),
(30, 'pi'),
(31, 'monero'),
(32, 'pepe'),
(33, 'uniswap'),
(34, 'okb'),
(35, 'aptos'),
(36, 'gatetoken'),
(37, 'bittensor'),
(38, 'ondo-finance'),
(39, 'near-protocol'),
(40, 'internet-computer'),
(41, 'kaspa'),
(42, 'ethereum-classic'),
(43, 'render'),
(44, 'polygon-ecosystem-token'),
(45, 'mantle'),
(46, 'aave'),
(47, 'crypto-com-coin'),
(48, 'vechain'),
(49, 'official-trump'),
(50, 'algorand'),
(51, 'filecoin'),
(52, 'ethena'),
(53, 'cosmos'),
(54, 'first-digital-usd'),
(55, 'celestia'),
(56, 'fetch'),
(57, 'arbitrum'),
(58, 'fantom'),
(59, 'kucoin-token'),
(60, 'dexe'),
(61, 'maker'),
(62, 'jupiter'),
(63, 'stacks'),
(64, 'xinfin-network'),
(65, 'optimism-ethereum'),
(66, 'fartcoin'),
(67, 'worldcoin-org'),
(68, 'bonk1'),
(69, 'wbnb'),
(70, 'eos'),
(71, 'flare'),
(72, 'story-protocol'),
(73, 'sei'),
(74, 'paypal-usd'),
(75, 'tether-gold'),
(76, 'injective-protocol'),
(77, 'the-graph'),
(78, 'quant'),
(79, 'curve-dao-token'),
(80, 'immutable-x'),
(81, 'binaryx-new'),
(82, 'pax-gold'),
(83, 'jasmy'),
(84, 'gala'),
(85, 'the-sandbox'),
(86, 'raydium'),
(87, 'nexo'),
(88, 'usual-usd'),
(89, 'kaia'),
(90, 'lido-dao'),
(91, 'iota'),
(92, 'theta'),
(93, 'helium'),
(94, 'bittorrent'),
(95, 'flow'),
(96, 'decentraland'),
(97, 'bitcoin-sv'),
(98, 'pancakeswap'),
(99, 'telcoin'),
(100, 'floki-inu');

